spring.application.name=scheduler
# ===============================
# = Database Configuration
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/db_major
spring.datasource.username=postgres
spring.datasource.password=ramdhani12

# ===============================
# = JPA / Hibernate Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

libreoffice.path=C:/Program Files/LibreOffice/program/soffice.exe

# Optional: ubah port server (kalau mau)
server.port=9090

